### ISSUE TITLE
[Feature] Add New Clash Rule Provider Format

### ISSUE THREAD

**Issue by Tirbod** [bootmortis/iran-hosted-domains#38]
### Description

Add a clash [rule provider](https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#rule-providers) with domain behavior and text format.

### Motivation

Domain behavior is [more efficient](https://github.com/Dreamacro/clash/issues/1838#issuecomment-998502273) for large numbers of rules and [new text format](https://lancellc.gitbook.io/clash/clash-config-file/rule-provider#format) have better matching performance and less memory usage. 

### Example
```
rule-providers:
  iran:
    type: http
    behavior: domain
    format: 'text'
    url: ""
    path: ./ruleset/iran.txt
    interval: 432000
```
Current  `clash_rules.yaml` would look like this with domain behavior and in text format:
[clash_rules.txt](https://github.com/bootmortis/iran-hosted-domains/files/11304782/clash_rules.txt)

### Suggested Solution

`classical`'s `DOMAIN-SUFFIX` equivalent is `+.` [wildcard](https://lancellc.gitbook.io/clash/clash-config-file/syntax#+-wildcard) in `domain`  .

### Additional Information

With domain behavior , `GEOIP` rule should be added separately.

### Additional Request
It would be great if another `clash_rules` file without `.ir` domains would be added, it would reduce file size and improve matching speed, and all `.ir` domains could be bypassed separately with `DOMAIN-SUFFIX,ir` .
